# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8598f22d16d626d639c1957ff3dcb0aabea7bdcc3f7117b834540fd4f1c94cf2f4fdd683d415bede43d6b123c9e2968df4415a7f51b816f3b3375e246d970bf6

test:
  secret_key_base: 3896273d5be62caa6c31e21af6b14c0883247d4618b1df66dccad34accb66a08c06f2bf658f7124334b0167795e50723bbf46e3e28ffdbab69c30994e0fdcda4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
